source "https://rubygems.org"

gem "sinatra"
gem "sqlite3"
gem "activerecord"
gem "sinatra-reloader"
gem "sinatra-activerecord"
gem "sinatra-contrib"
gem "rake"

#группа development не будет исполнена при хостинге веб-приложения 
#эта группа будет исполнена только при разработке 

group :development do 
	gem "tux"
end